Repository KyleMBoomer/art-collector, pull requests merged in 2024-07, with the labels that each got.

#7 Added styling for main gallery
  src/CSS/App.css
  src/CSS/ArtCard.css
  src/CSS/MainGallery.css
  src/Components/App.tsx
  src/Components/ArtCard.tsx
  src/Components/MainGallery.tsx
Labels: Design

#13 Feature/header and footer components
  src/CSS/Footer.css
  src/Components/App.tsx
  src/Components/Footer.tsx
  src/Images/github-icon.png
  src/Images/linkedin-icon.png
Labels: Add Components

#15 Updated stlying for MainPage and Header component
  src/CSS/MainPage.css
  src/Components/App.tsx
  src/Components/Header.tsx
  src/Components/MainPage.tsx
Labels: Design

#27 Feat/cypress test adjustments
  cypress/e2e/spec_MainGallery.cy.ts
  cypress/e2e/spec_MainPage.cy.ts
  cypress/fixtures/records.json
  src/Components/ApiCalls.tsx
  src/Components/MainGallery.tsx
Labels: bug, Cypress

#23 My Gallery Bug Fix
  src/Components/MainGallery.tsx
Labels: bug

#28 add loading rendering upon fetch wait
  src/CSS/MainGallery.css
  src/Components/MainGallery.tsx
  src/Components/MyGallery.tsx
  src/Utility/ApiCalls.ts
  src/Utility/Types.ts
Labels: bug, Design, Cypress

#35 Feat/no favorites warning & Accessibility enhancement
  src/CSS/Header.css
  src/CSS/MainPage.css
  src/Components/Header.tsx
  src/Components/MainGallery.tsx
  src/Components/MyGallery.tsx
Labels: Typescript, Accessibility

#44 Feat/minor styling adj
  src/CSS/ArtCard.css
  src/CSS/MainGallery.css
  src/CSS/MainPage.css
  src/Components/MainPage.tsx
Labels: Design

#45 Added animation to the loading message and deleted the old api call f…
  src/CSS/ArtCard.css
  src/CSS/FavoriteArtCard.css
  src/CSS/MainGallery.css
  src/Components/ApiCalls.tsx
  src/Components/MainGallery.tsx
  src/Utility/ApiCalls.ts
Labels: Design, Code Clean Up

#46 updated styling and error handling
  src/Assets/Van_Gogh_-_Trauernder_alter_Mann.jpeg
  src/Assets/sadman.webp
  src/CSS/MainGallery.css
  src/CSS/MyGallery.css
  src/Components/MainGallery.tsx
  src/Utility/ApiCalls.ts
Labels: Design

#48 updated testing and api call
  cypress/e2e/spec_ArtCard.cy.ts
  cypress/e2e/spec_MainGallery.cy.ts
  cypress/e2e/spec_MainPage.cy.ts
  cypress/e2e/spec_MyGallery.cy.ts
  src/CSS/ArtCard.css
  src/CSS/FavoriteArtCard.css
  src/CSS/MyGallery.css
  src/Utility/ApiCalls.ts
Labels: Network Request, Cypress, Code Clean Up
